# Generated by Django 6.0.1 on 2026-02-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
