# Generated by Django 6.0.1 on 2026-02-06 20:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendamentoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marcada", "Marcada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="marcada",
                        max_length=15,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_como_medico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_como_paciente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data_hora"],
                "unique_together": {("medico", "data_hora"), ("paciente", "data_hora")},
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condicao_paciente",
                    models.CharField(
                        choices=[
                            ("estavel", "Estável"),
                            ("instavel", "Instável"),
                            ("critica", "Crítica"),
                        ],
                        max_length=15,
                    ),
                ),
                ("descricao", models.TextField(max_length=1000)),
                (
                    "receita",
                    models.FileField(
                        blank=True, null=True, upload_to="consulta_receita/"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="consulta_arquivo/"
                    ),
                ),
                (
                    "protocolo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consulta",
                        to="consultas.agendamentoconsulta",
                    ),
                ),
            ],
        ),
    ]
