# Generated by Django 6.0.1 on 2026-02-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consulta_crm_medico_consulta_data_geracao_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='receita_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receitas/'),
        ),
    ]
