# Generated by Django 5.2.2 on 2026-02-14 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_consulta_receita_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamentoconsulta',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='data_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='status',
            field=models.CharField(choices=[('marcada', 'Marcada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('nao_realizada', 'Não Realizada')], db_index=True, default='marcada', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultalog',
            name='status_anterior',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='consultalog',
            name='status_novo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='agendamentoconsulta',
            constraint=models.UniqueConstraint(fields=('medico', 'data_hora'), name='unique_medico_horario'),
        ),
        migrations.AddConstraint(
            model_name='agendamentoconsulta',
            constraint=models.UniqueConstraint(fields=('paciente', 'data_hora'), name='unique_paciente_horario'),
        ),
    ]
