# Generated by Django 6.0.1 on 2026-02-18 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_alter_consulta_agendamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agendamentoconsulta',
            index=models.Index(fields=['medico', 'data_hora'], name='consultas_a_medico__f620bc_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamentoconsulta',
            index=models.Index(fields=['paciente', 'data_hora'], name='consultas_a_pacient_1684e8_idx'),
        ),
    ]
