# Generated by Django 6.0.1 on 2026-02-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_alter_consultalog_status_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultalog',
            name='status_anterior',
            field=models.CharField(choices=[('-', 'Inicial'), ('marcada', 'Marcada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('nao_realizada', 'Não Realizada'), ('receita_gerada', 'Receita Gerada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consultalog',
            name='status_novo',
            field=models.CharField(choices=[('-', 'Inicial'), ('marcada', 'Marcada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('nao_realizada', 'Não Realizada'), ('receita_gerada', 'Receita Gerada')], max_length=20),
        ),
    ]
