# Generated by Django 6.0.1 on 2026-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0011_alter_consultalog_status_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='status',
            field=models.CharField(choices=[('Marcada', 'Marcada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Não Realizada', 'Não Realizada')], db_index=True, default='Marcada', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='condicao_paciente',
            field=models.CharField(choices=[('Estável', 'Estável'), ('Instável', 'Instável'), ('Crítica', 'Crítica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='consultalog',
            name='status_anterior',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Marcada', 'Marcada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Não Realizada', 'Não Realizada'), ('Receita Gerada', 'Receita Gerada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consultalog',
            name='status_novo',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Marcada', 'Marcada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Não Realizada', 'Não Realizada'), ('Receita Gerada', 'Receita Gerada')], max_length=20),
        ),
    ]
