LIMITE_DIARIO_MEDICO = 9
ANTECEDENCIA_MINIMA_HORAS = 2


DIA_UTIL_FINAL = 4
HORA_INICIO_ATENDIMENTO = 8
HORA_FIM_ATENDIMENTO = 21
FORMATO_HORA = "%H:%M"
FORMATO_DATA = "%Y-%m-%d"
INTERVALO_MINUTOS = (0, 30)

CACHE_TIMEOUT_HORARIOS = 60

LOG_STATUS_INICIAL = "-"

PAGINACAO_PADRAO = 10

LABEL_CONDICAO_PACIENTE = "Condição do Paciente"
LABEL_DESCRICAO_CONSULTA = "Descrição da Consulta"
LABEL_RECEITA = "Receita"
LABEL_ARQUIVO = "Arquivo"
LABEL_SELECIONE_MEDICO = "Selecione o médico"
LABEL_DATA_DA_CONSULTA = "Data da Consulta"
LABEL_HORARIO = "Horário"

STATUS_LABEL_INICIAL = "Inicial"
STATUS_LABEL_MARCADA = "Marcada"
STATUS_LABEL_REALIZADA = "Realizada"
STATUS_LABEL_CANCELADA = "Cancelada"
STATUS_LABEL_NAO_REALIZADA = "Não Realizada"
STATUS_LABEL_RECEITA_GERADA = "Receita Gerada"
STATUS_LABEL_CONDICAO_PACIENTE_ESTAVEL = "Estável"
STATUS_LABEL_CONDICAO_PACIENTE_INSTAVEL = "Instável"
STATUS_LABEL_CONDICAO_PACIENTE_CRITICA = "Crítica"

