LIMITE_DIARIO_MEDICO = 9
ANTECEDENCIA_MINIMA_HORAS = 2


DIA_UTIL_FINAL = 4
HORA_INICIO_ATENDIMENTO = 8
HORA_FIM_ATENDIMENTO = 21
FORMATO_HORA = "%H:%M"
FORMATO_DATA = "%Y-%m-%d"
INTERVALO_MINUTOS = (0, 30)

CACHE_TIMEOUT_HORARIOS = 60

LOG_STATUS_INICIAL = "-"

PAGINACAO_PADRAO = 10
