# Generated by Django 6.0.1 on 2026-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_customuser_idade_alter_customuser_origem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telefone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
